version: '3'
services:
  proxy:
    build: ./proxy
    container_name: proxy_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    build: ./mysql
    container_name: db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  wordpress:
    build: ./wordpress
    container_name: wordpress_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: onya-lab.site
      VIRTUAL_PORT: "8080"
    depends_on:
      - db
